---
box:
  name:     "ubuntu-lts"
  username: "vagrant"

sizes:
  small:
    cpus:   1
    memory: 1024
  middle:
    cpus:   2
    memory: 2048
  large:
    cpus:   4
    memory: 4096

instances:
  - host: test
    size: small
