---
- name: Download the upload_progress_module source
  get_url:
    url: "{{ nginx_upload_progress_url }}"
    dest: "/tmp/nginx-upload-progress-module-{{ nginx_upload_progress_version }}.tar.gz"

- name: Unpack the upload_progress_module source
  command: tar -xvzf /tmp/nginx-upload-progress-module-{{ nginx_upload_progress_version }}.tar.gz chdir=/tmp creates=/tmp/nginx-upload-progress-module-{{ nginx_upload_progress_version }}

- name: Copy the upload_progress_module source folder
  command: sudo cp -R /tmp/nginx-upload-progress-module-{{ nginx_upload_progress_version }} /tmp/nginx_upload_progress

- name: Make sure the upload_progress_module configuration is updated
  template:
    src: ../../templates/modules/upload_progress.j2
    dest: "{{ nginx_dir }}/sites-available/upload_progress"
    owner: root
    group: root
    mode: 0644
