---
- name: Installs nvm dependencies
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - git
    - curl
    - build-essential
    - libssl-dev
  tags: nvm

- name: Installs nvm
  sudo: yes
  sudo_user: "{{ ansible_ssh_user }}"
  git:
    repo: https://github.com/creationix/nvm.git
    dest: ~/.nvm
    version: "v{{ nvm_version }}"
  tags: nvm

- name: Sources nvm in ~/.profile
  sudo: yes
  sudo_user: "{{ ansible_ssh_user }}"
  lineinfile:
    dest: ~/.profile
    line: "source ~/.nvm/nvm.sh"
  tags: nvm

- name: Installs node versions
  sudo: yes
  sudo_user: "{{ ansible_ssh_user }}"
  command: /bin/bash -c "source ~/.nvm/nvm.sh && nvm install {{ item }}"
  with_items: nvm_install
  tags: nvm

- name: Sets default node version
  sudo: yes
  sudo_user: "{{ ansible_ssh_user }}"
  command: /bin/bash -c "source ~/.nvm/nvm.sh && nvm alias default {{ nvm_default }}"
  tags: nvm
