---
- name: Updates the user privileges
  sudo: yes
  sudo_user: "{{ postgresql_admin_user }}"
  postgresql_user:
    name: "{{ item.name }}"
    db: "{{ item.db }}"
    port: "{{ postgresql_port }}"
    priv: "{{ item.priv | default('ALL') }}"
    state: present
    login_host: "{{ item.host | default('localhost') }}"
    login_user: "{{ postgresql_admin_user }}"
    role_attr_flags: "{{ item.role_attr_flags | default('') }}"
  with_items: postgresql_user_privileges
  when: postgresql_users | length > 0
