---
- name: Makes sure the postgis extensions are installed
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - libgeos-c1
    - "postgresql-{{ postgresql_version }}-postgis-{{ postgresql_ext_postgis_version }}"
    - "postgresql-{{ postgresql_version }}-postgis-{{ postgresql_ext_postgis_version }}-scripts"
  notify:
    - restart postgresql
