---
- name: Add vagrant host to local /etc/hostd
  sudo: yes
  local_action: lineinfile
                state=present
                dest=/etc/hosts
                regexp="^(?:[0-9]{1,3}\.){3}[0-9]{1,3} {{ ips[ansible_hostname]['domain'] }}$"
                line="{{ ips[ansible_hostname]['ip'] }} {{ ips[ansible_hostname]['domain'] }}"
