---
# Midnight Commander

- name: Install Midnight Commander
  apt:
    name: "mc"
    state: "latest"
  tags:
    - workspace

# htop

- name: Install htop
  apt:
    name: "htop"
    state: "latest"
  tags:
    - workspace

# Neovim

- name: Add neovim repository
  apt_repository:
    repo: "ppa:neovim-ppa/unstable"
  tags:
    - workspace

- name: Install neovim
  apt:
    name: "neovim"
    state: "latest"
  tags:
    - workspace

- name: Install neovim as alternative for vi, vim and editor
  command: "update-alternatives --install /usr/bin/{{ item }} {{ item }} /usr/bin/nvim 60"
  with_items:
    - vi
    - vim
    - editor
  tags:
    - workspace

- name: Configure vi, vim and editor alternative
  command: "update-alternatives --auto {{ item }}"
  with_items:
    - vi
    - vim
    - editor
  tags:
    - workspace

# Configuration files

- name: Clone configuration files repository
  sudo: yes
  sudo_user: "{{ user }}"
  git:
    repo: "https://github.com/demiazz/dotfiles.git"
    dest: "/tmp/dotfiles"
  tags:
    - workspace

- name: Copy git configuration files
  sudo: yes
  sudo_user: "{{ user }}"
  command: "cp /tmp/dotfiles/.gitconfig ~"
  tags:
    - workspace

- name: Copy .gitignore file
  sudo: yes
  sudo_user: "{{ user }}"
  command: "cp /tmp/dotfiles/.gitignore ~"
  tags:
    - workspace

- name: Copy .nvimrc file
  sudo: yes
  sudo_user: "{{ user }}"
  command: "cp /tmp/dotfiles/.nvimrc ~"
  tags:
    - workspace

- name: Install nvim plug manager dependency
  apt:
    name: "curl"
    state: "latest"
  tags:
    - workspace
