---
# Midnight Commander

- name: Install Midnight Commander
  apt:
    name: "mc"
    state: "latest"

# htop

- name: Install htop
  apt:
    name: "htop"
    state: "latest"

# Neovim

- name: Install neovim dependencies
  apt:    
    name: "{{ item }}"
    state: "latest"
  with_items:
    - python-pip
    - libpython-dev
    - silversearcher-ag

- name: Add neovim repository
  apt_repository:
    repo: "ppa:neovim-ppa/unstable"

- name: Install neovim
  apt:
    name: "neovim"
    state: "latest"

- name: Install python-neovim
  command: pip install neovim

- name: Install neovim as alternative for vi, vim and editor
  command: "update-alternatives --install /usr/bin/{{ item }} {{ item }} /usr/bin/nvim 60"
  with_items:
    - vi
    - vim
    - editor

- name: Configure vi, vim and editor alternative
  command: "update-alternatives --auto {{ item }}"
  with_items:
    - vi
    - vim
    - editor

# Configuration files

- name: Clone configuration files repository
  sudo: yes
  sudo_user: "{{ ansible_ssh_user }}"
  git:
    repo: "https://github.com/demiazz/dotfiles.git"
    dest: "/tmp/dotfiles"

- name: Copy git configuration files
  sudo: yes
  sudo_user: "{{ ansible_ssh_user }}"
  command: "cp /tmp/dotfiles/.gitconfig ~"

- name: Copy .gitignore file
  sudo: yes
  sudo_user: "{{ ansible_ssh_user }}"
  command: "cp /tmp/dotfiles/.gitignore ~"

- name: Copy .nvimrc file
  sudo: yes
  sudo_user: "{{ ansible_ssh_user }}"
  command: "cp /tmp/dotfiles/.nvimrc ~"
