---
- name: Copy private SSH key
  sudo: yes
  sudo_user: "{{ ansible_ssh_user }}"
  copy:
    src: "~/.ssh/id_rsa"
    dest: "~/.ssh/id_rsa"
    owner: "{{ ansible_ssh_user }}"
    group: "{{ ansible_ssh_user }}"
    mode: "u=rw,g=,o="

- name: Copy public SSH key
  sudo: yes
  sudo_user: "{{ ansible_ssh_user }}"
  copy:
    src: "~/.ssh/id_rsa.pub"
    dest: "~/.ssh/id_rsa.pub"
    owner: "{{ ansible_ssh_user }}"
    group: "{{ ansible_ssh_user }}"
    mode: "u=rw,g=,o="

- name: Fix access rights for .ssh
  sudo: yes
  sudo_user: "{{ ansible_ssh_user }}"
  file:
    path: "~/.ssh"
    owner: "{{ ansible_ssh_user }}"
    group: "{{ ansible_ssh_user }}"
    mode: "u=rwx,g=,o="
