---
- include: package.yml
  when: nginx_install_method == "package"

- include: source.yml
  when: nginx_install_method == "source"

- include: scripts.yml
- include: configure.yml
- include: default-site.yml
- include: sites.yml
