---
- name: Make sure the ansible required dependencies are installed
  apt:
    pkg: python-pycurl
    state: present

- name: Add the nginx repository
  apt_repository:
    repo: ppa:nginx/stable

- include: directories.yml

- name: Make sure nginx is installed (package)
  apt:
    pkg: nginx
    state: present
  notify:
    - restart nginx
