---
- name: Create scala lib dir
  file:
    path: "{{ scala_lib_path }}"
    state: directory
  tags:
    - scala

- name: "Clean existing Scala"
  file:
    path: "{{ scala_lib_path_target }}"
    state: absent
  tags:
    - scala

- name: Download Scala distribution
  get_url:
    url: "{{ scala_download_url }}"
    dest: "/tmp/{{ scala_archive_file }}"
    force: no
  tags:
    - scala

- name: Unpack Scala
  command: tar -xvf {{ scala_archive_file }}
  args:
    chdir: /tmp/
  tags:
    - scala

- name: Move (by force) Scala to lib
  command: mv /tmp/{{ scala_version_name }} {{ scala_lib_path_target }}
  args:
    chdir: /tmp/
  tags:
    - scala

- name: Link scala
  command: ln -sf {{ scala_lib_path_target }}/bin/scala {{ scala_link_target }}
  tags:
    - scala

- name: Link scalac
  command: ln -sf {{ scala_lib_path_target }}/bin/scalac {{ scala_link_target }}
  tags:
    - scala

- name: Link fsc
  command: ln -sf {{ scala_lib_path_target }}/bin/fsc {{ scala_link_target }}
  tags:
    - scala

- name: Link sbaz
  command: ln -sf {{ scala_lib_path_target }}/bin/sbaz {{ scala_link_target }}
  tags:
    - scala

- name: Link sbaz-setup
  command: ln -sf {{ scala_lib_path_target }}/bin/sbaz-setup {{ scala_link_target }}
  tags:
    - scala

- name: Link scaladoc
  command: ln -sf {{ scala_lib_path_target }}/bin/scaladoc {{ scala_link_target }}
  tags:
    - scala

- name: Link scalap
  command: ln -sf {{ scala_lib_path_target }}/bin/scalap {{ scala_link_target }}
  tags:
    - scala
