---
- name: Add BinTray repository
  apt_repository:
    repo: "deb http://dl.bintray.com/sbt/debian /"
    state: present
  tags:
    - scala
    - sbt

- name: Install sbt
  apt:
    name: sbt
    force: yes
    update_cache: yes
    state: latest
  tags:
    - scala
    - sbt
